def inner_wrapper(row,strategyclass,telegramid):
    logging.info('signalmaker started')
    s1=signalmaker(row,strategyclass)
    logging.info('duplichecker started')
    s2=duplichecker(s1)
    logging.info('stringmaker started')
    s3=stringmaker(s2)
    logging.info('telesender started')
    telesender(s3,telegramid)
    logging.info('All finished; Going into sleep mode')
    time.sleep(strategyclass.timer)